class ProfileRepository:
    def create(self, db, obj_in): ...
    def get_by_id(self, db, profile_id: int): ...
    def list(self, db, skip=0, limit=20): ...
    def update(self, db, db_obj, obj_in): ...
    def delete(self, db, db_obj): ...