"""create trigger rules and active logs

Revision ID: 32462a97d7df
Revises: f52af6237a54
Create Date: 2026-04-11 11:05:35.711260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32462a97d7df'
down_revision: Union[str, Sequence[str], None] = 'f52af6237a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trigger_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_rules_enabled'), 'trigger_rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_trigger_rules_id'), 'trigger_rules', ['id'], unique=False)
    op.create_index(op.f('ix_trigger_rules_priority'), 'trigger_rules', ['priority'], unique=False)
    op.create_index(op.f('ix_trigger_rules_trigger_type'), 'trigger_rules', ['trigger_type'], unique=False)
    op.create_table('active_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trigger_rule_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trigger_rule_id'], ['trigger_rules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_logs_created_at'), 'active_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_active_logs_id'), 'active_logs', ['id'], unique=False)
    op.create_index(op.f('ix_active_logs_status'), 'active_logs', ['status'], unique=False)
    op.create_index(op.f('ix_active_logs_trigger_rule_id'), 'active_logs', ['trigger_rule_id'], unique=False)
    op.create_index(op.f('ix_active_logs_user_id'), 'active_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_active_logs_user_id'), table_name='active_logs')
    op.drop_index(op.f('ix_active_logs_trigger_rule_id'), table_name='active_logs')
    op.drop_index(op.f('ix_active_logs_status'), table_name='active_logs')
    op.drop_index(op.f('ix_active_logs_id'), table_name='active_logs')
    op.drop_index(op.f('ix_active_logs_created_at'), table_name='active_logs')
    op.drop_table('active_logs')
    op.drop_index(op.f('ix_trigger_rules_trigger_type'), table_name='trigger_rules')
    op.drop_index(op.f('ix_trigger_rules_priority'), table_name='trigger_rules')
    op.drop_index(op.f('ix_trigger_rules_id'), table_name='trigger_rules')
    op.drop_index(op.f('ix_trigger_rules_enabled'), table_name='trigger_rules')
    op.drop_table('trigger_rules')
    # ### end Alembic commands ###
