"""create proactive windows and messages

Revision ID: d22717b4ee61
Revises: 32462a97d7df
Create Date: 2026-04-13 10:11:36.671176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22717b4ee61'
down_revision: Union[str, Sequence[str], None] = '32462a97d7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proactive_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trigger_rule_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('displayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trigger_rule_id'], ['trigger_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proactive_messages_created_at'), 'proactive_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_proactive_messages_id'), 'proactive_messages', ['id'], unique=False)
    op.create_index(op.f('ix_proactive_messages_status'), 'proactive_messages', ['status'], unique=False)
    op.create_index(op.f('ix_proactive_messages_trigger_rule_id'), 'proactive_messages', ['trigger_rule_id'], unique=False)
    op.create_index(op.f('ix_proactive_messages_user_id'), 'proactive_messages', ['user_id'], unique=False)
    op.create_table('proactive_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=False),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=False),
    sa.Column('max_trigger_per_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proactive_windows_id'), 'proactive_windows', ['id'], unique=False)
    op.create_index(op.f('ix_proactive_windows_user_id'), 'proactive_windows', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proactive_windows_user_id'), table_name='proactive_windows')
    op.drop_index(op.f('ix_proactive_windows_id'), table_name='proactive_windows')
    op.drop_table('proactive_windows')
    op.drop_index(op.f('ix_proactive_messages_user_id'), table_name='proactive_messages')
    op.drop_index(op.f('ix_proactive_messages_trigger_rule_id'), table_name='proactive_messages')
    op.drop_index(op.f('ix_proactive_messages_status'), table_name='proactive_messages')
    op.drop_index(op.f('ix_proactive_messages_id'), table_name='proactive_messages')
    op.drop_index(op.f('ix_proactive_messages_created_at'), table_name='proactive_messages')
    op.drop_table('proactive_messages')
    # ### end Alembic commands ###
